baseURL = '/'
relativeURLs = true
locale = 'en-us'
title = 'Red Earth'
theme = 'paper'

[menu]
  [[menu.main]]
    name = "About"
    pageRef = "/about/"

[params]
  color = 'wheat'
  github = 'redelfive0'
  rss = true
  name = 'Red Earth'
  bio = 'Just for fun'
